export const APP_ERROR = 'APP_ERROR';
export const ALERT = 'ALERT';

export const AUTH_SEND = 'AUTH_SEND';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CLEAR = 'AUTH_CLEAR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_SUCCESS = 'AUTH_CLEAR_SUCCESS';
export const AUTH_STORE_COOKIE = 'AUTH_STORE_COOKIE';
export const AUTH_STORE_COOKIE_SUCCESS = 'AUTH_STORE_COOKIE_SUCCESS';
export const AUTH_STORE_COOKIE_FAIL = 'AUTH_STORE_COOKIE_FAIL';
export const AUTH_BY_COOKIE = 'AUTH_BY_COOKIE';
export const AUTH_BY_COOKIE_SUCCESS = 'AUTH_BY_COOKIE_SUCCESS';
export const AUTH_BY_COOKIE_FAIL = 'AUTH_BY_COOKIE_FAIL';
export const AUTH_CHECK_COOKIE = 'AUTH_CHECK_COOKIE';
export const AUTH_CHECK_COOKIE_SUCCESS = 'AUTH_CHECK_COOKIE_SUCCESS';
export const AUTH_CHECK_COOKIE_FAIL = 'AUTH_CHECK_COOKIE_FAIL';

export const PLAN_LOAD = 'PLAN_LOAD';
export const PLAN_LOAD_SUCCESS = 'PLAN_LOAD_SUCCESS';
export const PLAN_LOAD_FAIL = 'PLAN_LOAD_FAIL';
export const PLAN_PERSIST_FEEDBACK = 'PLAN_PERSIST_FEEDBACK';
export const PLAN_PERSIST_FEEDBACK_SUCCESS = 'PLAN_PERSIST_FEEDBACK_SUCCESS';
export const PLAN_PERSIST_FEEDBACK_FAIL = 'PLAN_PERSIST_FEEDBACK_FAIL';
export const PLAN_END_WORKOUT = 'PLAN_END_WORKOUT';
export const PLAN_END_WORKOUT_SUCCESS = 'PLAN_END_WORKOUT_SUCCESS';
export const PLAN_END_WORKOUT_FAIL = 'PLAN_END_WORKOUT_FAIL';
export const PLAN_START_WORKOUT = 'PLAN_START_WORKOUT';
export const PLAN_START_WORKOUT_SUCCESS = 'PLAN_START_WORKOUT_SUCCESS';
export const PLAN_START_WORKOUT_FAIL = 'PLAN_START_WORKOUT_FAIL';
export const PLAN_UPDATE_SET = 'PLAN_UPDATE_SET';
export const PLAN_UPDATE_SET_SUCCESS = 'PLAN_UPDATE_SET_SUCCESS';
export const PLAN_UPDATE_SET_FAIL = 'PLAN_UPDATE_SET_FAIL';
export const PLAN_CHECK_SET = 'PLAN_CHECK_SET';
export const PLAN_CHECK_SET_SUCCESS = 'PLAN_CHECK_SET_SUCCESS';
export const PLAN_CHECK_SET_FAIL = 'PLAN_CHECK_SET_FAIL';
export const PLAN_CHECK_SET_WITH_VALUE = 'PLAN_CHECK_SET_WITH_VALUE';
export const PLAN_CHECK_SET_WITH_VALUE_SUCCESS = 'PLAN_CHECK_SET_WITH_VALUE_SUCCESS';
export const PLAN_CHECK_SET_WITH_VALUE_FAIL = 'PLAN_CHECK_SET_WITH_VALUE_FAIL';

export const HABIT_FETCH_ALL = 'HABIT_FETCH_ALL';
export const HABIT_FETCH_ALL_SUCCESS = 'HABIT_FETCH_ALL_SUCCESS';
export const HABIT_FETCH_ALL_FAIL = 'HABIT_FETCH_ALL_FAIL';
export const HABIT_FETCH_STARTED = 'HABIT_FETCH_STARTED';
export const HABIT_FETCH_STARTED_SUCCESS = 'HABIT_FETCH_STARTED_SUCCESS';
export const HABIT_FETCH_STARTED_FAIL = 'HABIT_FETCH_STARTED_FAIL';
export const HABIT_CHECK = 'HABIT_CHECK';
export const HABIT_CHECK_SUCCESS = 'HABIT_CHECK_SUCCESS';
export const HABIT_CHECK_FAIL = 'HABIT_CHECK_FAIL';
export const HABIT_START = 'HABIT_START';
export const HABIT_START_SUCCESS = 'HABIT_START_SUCCESS';
export const HABIT_START_FAIL = 'HABIT_START_FAIL';

export const DASHBOARD_PREV_WEEK = 'DASHBOARD_PREV_WEEK';
export const DASHBOARD_NEXT_WEEK = 'DASHBOARD_NEXT_WEEK';
export const DASHBOARD_SET_WEEK = 'DASHBOARD_SET_WEEK';
export const DASHBOARD_INIT_WEEK = 'DASHBOARD_INIT_WEEK';

export const NETWORK_REQUEST = 'NETWORK_REQUEST';
export const NETWORK_REQUEST_COMPLETED = 'NETWORK_REQUEST_COMPLETED';

export const COUNTERS_START = 'COUNTERS_START';
export const COUNTERS_STOP = 'COUNTERS_STOP';
export const COUNTERS_RESUME = 'COUNTERS_RESUME';
export const COUNTERS_RESET = 'COUNTERS_RESET';
export const COUNTERS_TICK = 'COUNTERS_TICK';
